### ISSUE TITLE
Panhandler does not appear to recognise "Max" as an acceptable SSL Protocol version

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#118]
## Describe the bug

The firewall's SSL decryption policy has the SSL Protocol Max Version set to "Max".

Panhandler reports this as a failure; from observation it appears to be explicitly expecting "TLSv1.3".

This is with Panhandler version 4.4 2021-05-20T15:24:19, running against a PA-220 with PAN-OS 10.1.0

Screenshots attached.

- Version used: 4.4 2021-05-20T15:24:19

![Panhandler_decryption](https://user-images.githubusercontent.com/29375176/121650979-0aca5400-ca92-11eb-8a61-99dd36214da3.PNG)

**Comment by scotchoaf** [comment]
Hi, can you give more info about how you loaded ironSkillet to the device and if it had an existing configuration? We've tested locally and didn't see the issue. Do want to try and replicate.

Also what error did you get from panhandler?

In the config element we push, it does explicitly use tls 1.3 as the max version. There are often variations between what the UI will show vs how the API/CLI show the value. Could you also use the CLI show command to see if Max appears there?

https://github.com/PaloAltoNetworks/iron-skillet/blob/f7bb805ac5ed0f2b44e4b438f8c021eaf2f5c66b/templates/panos/snippets/.meta-cnc.yaml#L887

**Comment by wegotourselvesareader** [comment]
Some time back (PAN-OS 9.1) I applied the recommended Iron Skillet configuration manually to the firewall, by copying/pasting the "set" commands from the .conf file in the loadable_configs folder. That configuration stayed unchanged during an upgrade from 9.1 to 10.0, and again from 10.0 to 10.1. I figured it was probably now a good time to revisit Iron Skillet and see what configuration could benefit from being updated.

The SSL Protocol setting I changed manually in the GUI. The firewall's CLI shows this:
```
admin@pa-220# show profiles decryption Recommended_Decryption_Profile ssl-protocol-settings
ssl-protocol-settings {
  min-version tls1-3;
  keyxchg-algo-rsa no;
  enc-algo-3des no;
  enc-algo-rc4 no;
  auth-algo-sha1 no;
  max-version max;
  keyxchg-algo-dhe no;
  enc-algo-aes-128-cbc no;
  enc-algo-aes-256-cbc no;
  enc-algo-chacha20-poly1305 yes;
}
```

Panhandler didn't throw any errors when checking; it merely indicated that the relevant check had failed (as shown in the screenshot in the initial report).

**Comment by BoraMutluoglu** [comment]
Hi morrisalex, I just tried to replicate this issue you are hitting. I loaded a v10.0 Iron-Skillet for NGFW baseline configuration to my VM-100(PAN-OS 10.1). As you and Scott both confirmed the default value being passed in is "TLSv1.3". I changed this value to be "max" within the v10.0 IronSkillet full config for NGFW and ran it against my VM-100. The Recommended_Decryption_Profile->SSL Protocol Settings->Protocol Version->max Version was set as "max" with no errors or warnings being thrown on the PanHandler side.
<img width="920" alt="Screen Shot 2021-06-11 at 10 51 43 AM" src="https://user-images.githubusercontent.com/38056262/121729186-0490a380-caa3-11eb-82a6-12c952325f7b.png">

doing a show command on the cli also shows that indeed the max-version has been correctly set to "max"

<img width="639" alt="Screen Shot 2021-06-11 at 10 52 52 AM" src="https://user-images.githubusercontent.com/38056262/121729309-2db13400-caa3-11eb-9763-392266cc3222.png">

I'm wondering if maybe updating your PanHandler to the latest version might fix this issue because I am not able to replicate it locally. Please let me know if that helps with anything.

**Comment by wegotourselvesareader** [comment]
This morning I updated to Panhandler version 4.5 2021-06-11T19:29:39 and ran the check again. It still reports a failure for the SSL Protocol Max Version. But now there's a difference: there's a new tooltip introduced in Panhandler which wasn't there in the older version when I first raised this issue.

![Panhandler_3](https://user-images.githubusercontent.com/29375176/121771044-e55a4a80-cb64-11eb-97bd-d26e9a854dba.png)

The tooltip explicitly states that the value should be v1.3 and _**not**_ max.


The firewall's own built-in documentation recommends setting that value to "Max" to automatically accommodate improvments in the supported protocols.

![firewall_max_version](https://user-images.githubusercontent.com/29375176/121771052-eb502b80-cb64-11eb-8490-d184cc5100c1.PNG)


I suggest that, where it is appropriate, Panhandler should be able to cope with two different values for the same setting. In the case of this particular setting for this particular PAN-OS version, Panhandler should report a successful check if the value is either v1.3 or max.

**Comment by wegotourselvesareader** [comment]
I noticed that there's a 10.1 branch here (missed it yesterday for some reason), so I also updated the skillet collection in Panhandler from 10.0 to 10.1 and ran the checks again. The check still fails for the same reason, with the same tooltip.

**Comment by BoraMutluoglu** [comment]
Hello morrisalex, I will be taking a look into fixing this issue in the 10.1 branch IronSkillet validation script today. I will update you with any changes. Thanks

**Comment by BoraMutluoglu** [comment]
Hello, I just updated the validation skillet and tested it against my NGFW with protocol max version set to "max" instead of tls1-3. My validations all passed successfully. Please update the repository and let me know if your issue persists. Thanks!
<img width="1128" alt="Screen Shot 2021-06-14 at 9 39 46 AM" src="https://user-images.githubusercontent.com/38056262/121927910-76abf700-ccf4-11eb-9393-bb1f48421b3b.png">

**Comment by wegotourselvesareader** [comment]
Thank you for fixing this; I've updated the local repository and the check now passes as indicated in your screenshot. However, there's another issue, which I'll raise a separate ticket for...
